version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ember-auto-import
  - dependency-name: ember-cli
  - dependency-name: ember-data
  - dependency-name: ember-source
  - dependency-name: eslint
    versions:
    - 8.x
  - dependency-name: husky
