version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ember-cli
    versions:
    - "*"
  - dependency-name: ember-data
    versions:
    - "*"
  - dependency-name: ember-source
    versions:
    - "*"
